header = """
/* sector_builder_ffi Header */

#ifdef __cplusplus
extern "C" {{
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "SECTOR_BUILDER_FFI_H"
include_version = true
language = "C"

[export]
prefix = "sector_builder_ffi_"

[parse]
parse_deps = true
include = ["sector-builder", "filecoin-proofs-ffi"]
